### ISSUE TITLE
Main repo's name

### ISSUE THREAD

**Issue by ninamiolane** [compSPI/compSPI#1]
Maybe let's use the same name for the organization and the main repo, i.e. compSPI and compSPI?

I believe this is standard in python libraries, see for example scikit-learn/scikit-learn:
https://github.com/scikit-learn/scikit-learn

**Comment by rdeeban** [comment]
The main repo has been renamed to compSPI.

**Comment by ninamiolane** [comment]
Awesome, thanks!! 🎉
