### ISSUE TITLE
clean up src/

### ISSUE THREAD

**Issue by fredericpoitevin** [compSPI/compSPI#24]
Most code in `src/` is obsolete or has been moved elsewhere. Remove unnecessary files/code.

**Comment by geoffwoollard** [comment]
I have plans to port the numpy simulate code to pytorch and include in simSPI. Specifically: `gauss_forward_model.py, simulate.py`

Should I stash things on a dev branch and remote this from compSPI main?

**Comment by fredericpoitevin** [comment]
Yes please @geoffwoollard

**Comment by geoffwoollard** [comment]
@fredericpoitevin ok I made a branch to clean up src on my fork and can PR it eventually. I removed some things I wrote. what else should I remove? 
branch to clean things up and merge eventually: https://github.com/geoffwoollard/compSPI/tree/clean_up_src/src
branch to stash things https://github.com/geoffwoollard/compSPI/tree/stash_simulate/src

**Comment by fredericpoitevin** [comment]
Thanks @geoffwoollard this looks like a good example of what we should do for the rest as well.

Is there anything in there that should be moved to other repos?

**Comment by geoffwoollard** [comment]
I looked at other files in `src`. I thin Nina or Nicolas wrote much of it. All my stuff is stashed away.

**Comment by fredericpoitevin** [comment]
Thanks @geoffwoollard !!! I think a lot of it I also already moved to https://github.com/compSPI/article-CVPR-workshop-2020 but did not remove from the repo. I'll have a second look.
